### ISSUE TITLE
Automate releases and push released charts to separate branch

### ISSUE THREAD

**Issue by tenstad** [Informasjonsforvaltning/helm-chart#45]
Suggestion:
 - Only source files in main
 - Merge to main workflow creates new release, pushing packaged charts to separate branch
 - The packaged-charts branch is hosted with github pages, and used in other workflows

https://helm.sh/docs/howto/chart_releaser_action/

**Comment by valosnah** [comment]
Planen er å på sikt fase helm-charts ut helt, så vi kan trygt lukke denne.
